### ISSUE TITLE
power armor

### ISSUE THREAD

**Issue by johnfg2610** [MyM-ModpackTeam/Civilization#1]
im not sure how this can be fixed but power armor loses the soulbound enchantment when used this is a complaint from many players which is quite fustrating

**Comment by Slind14** [comment]
From what I know, you can't enchant the power armor, it will loose all enchantments.

**Comment by johnfg2610** [comment]
is there no possible fix?

**Comment by Sir-Will** [comment]
You would need to ask the mod author, mod is on latest version.

**Comment by johnfg2610** [comment]
i think it would be better off coming from you @SirWilli or @Slind14 your well respected in the community and will be listened to

**Comment by Sir-Will** [comment]
It will make no difference.
