### ISSUE TITLE
dogs from doggystyle despawn

### ISSUE THREAD

**Issue by johnfg2610** [MyM-ModpackTeam/Civilization#2]
dogs from doggystyle despawn making the mod useless for all intents and purposes

**Comment by Slind14** [comment]
I assume this is on the server? (or single player, too?)

**Comment by Krhymez** [comment]
This is on the server. I will implement the crafting recipes for the dog eggs.

**Comment by johnfg12** [comment]
if im correct dont you level the dogs up?

**Comment by johnfg12** [comment]
or am i thinking of a diffrent mod
