### ISSUE TITLE
steves workshop

### ISSUE THREAD

**Issue by johnfg2610** [MyM-ModpackTeam/Civilization#26]
give steves workshop block a name

**Comment by Bennyboy1695** [comment]
can be done with minetweaker ;)
StevesWorkshop:production_table.displayName = "Production Table";

**Comment by johnfg2610** [comment]
Yup just noted it down so I remember

**Comment by johnfg2610** [comment]
https://github.com/MyM-ModpackTeam/Civilization/commit/70405e42b86a29dda30f1b4eb9d2711026eda8d2
fixed
