### ISSUE TITLE
Ancient Warfare

### ISSUE THREAD

**Issue by Demonica6666** [MyM-ModpackTeam/Civilization#34]
When you place an Ancient Warfare gate down, you cannot remove it even though it says to use a pick

**Comment by johnfg2610** [comment]
I'll look into it tonight sorry for any inconvenience

**Comment by johnfg2610** [comment]
Also if you have a issue with the pack could you allow us time to investigate and not bother mod devs/there githubs this allows use to check if it is a mistake we have made or a mod compact issue and if it is a problem with the mod we will deal with it thanks :)
https://github.com/shadowmage45/AncientWarfare2/issues/478

**Comment by johnfg2610** [comment]
this sorted? il close it and if what was suggested on ancient warfare's github doesn't work il investigate further
