### ISSUE TITLE
Mariculture Crucible Furnace - GUI FPS Issue

### ISSUE THREAD

**Issue by Sir-Will** [MyM-ModpackTeam/Civilization#5]
Opening the crucible furnace decreases the FPS a lot.

https://youtu.be/-kM1r4_qpYY

**Comment by johnfg2610** [comment]
may need to be reported as issue here https://github.com/joshiejack/Mariculture/issues

**Comment by johnfg2610** [comment]
cause 60 to 1 or 2 is not normal

**Comment by johnfg2610** [comment]
would u like me to test in my new version of the pack?

**Comment by Sir-Will** [comment]
Thats why I created the issue here. So someone can test it on the latest mariculture version and report it then to the author if the issue is there too.

**Comment by johnfg2610** [comment]
ok then on it

**Comment by johnfg2610** [comment]
after testing on the latest version there is still a significant fps drop

**Comment by johnfg2610** [comment]
il go and make a issue on mariculres github

**Comment by johnfg2610** [comment]
this issue can be closed ive reported it to mod devs github here
https://github.com/joshiejack/Mariculture/issues/340

**Comment by johnfg2610** [comment]
it would appear the mod is no longer under active development

**Comment by johnfg2610** [comment]
mod no longer under active development. closing ticket
